# This is a wrapper yml for `perf-wasm-jobs`, which has all the perf related
# wasm jobs. This file is essentially so we can point the pipeline in azdo
# UI to this, and thus avoid any scheduled triggers

parameters:
- name: performanceRepoBranch
  displayName: Performance Repo Branch
  type: string
  default: 'refs/heads/main'
- name: performanceRepoSource
  displayName: Performance Repo Source
  type: string
  default: ado
  values:
  - ado
  - github

trigger: none

pr:
  branches:
    include:
    - main
  paths:
    include:
    - eng/pipelines/runtime-wasm-perf.yml
    - eng/pipelines/coreclr/perf*.yml
    - eng/pipelines/coreclr/templates/perf-job.yml
    - eng/pipelines/coreclr/templates/run-perf*
    - eng/pipelines/coreclr/templates/run-scenarios-job.yml
    - eng/testing/performance/*
    - eng/testing/ChromeVersions.props

variables:
  - template: /eng/pipelines/common/variables.yml

resources:
  repositories:
  - repository: GithubPerformanceRepo
    type: github
    endpoint: dotnet
    name: dotnet/performance
    ref: '${{ parameters.performanceRepoBranch }}'
  - repository: InternalPerformanceRepo
    type: git
    name: dotnet-performance
    ref: '${{ parameters.performanceRepoBranch }}'

extends:
  template:  /eng/pipelines/common/templates/pipeline-with-resources.yml
  parameters:
    stages:
    - stage: Build
      jobs:
      - template: /eng/pipelines/coreclr/perf-wasm-jobs.yml
        parameters:
          runProfile: 'v8'
          collectHelixLogsScript: ${{ variables._wasmCollectHelixLogsScript }}
          onlySanityCheck: true
          performanceRepoSource: ${{ parameters.performanceRepoSource }}
          #downloadSpecificBuild:
            #buildId: '1878694'
            #pipeline: 'perf-wasm'
            #branchName: 'refs/pull/72119/head'
